# Linear Algebra Coding Lab: NumPy & TensorFlow
**Companion to Lab 1**

While the theoretical lab focuses on manual calculations to understand the *mechanics*, this coding lab focuses on the *tools* you will use in actual Deep Learning planning and implementation.

**Libraries:**
* **NumPy:** The fundamental package for scientific computing in Python.
* **TensorFlow:** An end-to-end open source platform for machine learning (Google).

---


In [1]:
# 0. Setup and Imports
import numpy as np
import tensorflow as tf

print(f"NumPy Version: {np.__version__}")
print(f"TensorFlow Version: {tf.__version__}")

ModuleNotFoundError: No module named 'numpy'

## Part 1: Defining Scalars, Vectors, Matrices, and Tensors

In the lecture, we defined these based on their dimensionality.
* **Scalar:** Rank 0 (Just a number)
* **Vector:** Rank 1 (1D Array)
* **Matrix:** Rank 2 (2D Array)
* **Tensor:** Rank n (n-Dimensional Array)

In [ ]:
# --- NUMPY IMPLEMENTATION ---

# 1. Scalar
scalar_np = np.array(5)

# 2. Vector (1D)
vector_np = np.array([1, 2, 3])

# 3. Matrix (2D) - 2 rows, 3 columns
matrix_np = np.array([[1, 2, 3],
                      [4, 5, 6]])

# 4. Tensor (3D) - e.g., representing an image (2x2 pixels, 3 color channels)
tensor_np = np.array([[[1, 0, 0], [0, 1, 0]],
                      [[0, 0, 1], [1, 1, 1]]])

print(f"Scalar Shape: {scalar_np.shape}, Rank: {scalar_np.ndim}")
print(f"Vector Shape: {vector_np.shape}, Rank: {vector_np.ndim}")
print(f"Matrix Shape: {matrix_np.shape}, Rank: {matrix_np.ndim}")
print(f"Tensor Shape: {tensor_np.shape}, Rank: {tensor_np.ndim}")

Scalar Shape: (), Rank: 0
Vector Shape: (3,), Rank: 1
Matrix Shape: (2, 3), Rank: 2
Tensor Shape: (2, 2, 3), Rank: 3


In [ ]:
# --- TENSORFLOW IMPLEMENTATION ---
# In Deep Learning, we use Tensors (constant or variable)

matrix_tf = tf.constant([[1, 2, 3],
                         [4, 5, 6]])

print("\n--- TensorFlow Object ---")
print(matrix_tf)
print(f"Shape: {matrix_tf.shape}")
print(f"Rank: {tf.rank(matrix_tf)}")

In [ ]:
# ----- Vector Operations ---------

# Define three vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.array([7, 8, 9])

# Calculate dot product using numpy.dot() function
dot_product_AB = np.dot(A, B)
dot_product_BA = np.dot(B, A)

print(dot_product_AB)
print(dot_product_BA)

# Check commutative property: A • B = B • A
if dot_product_AB == dot_product_BA:
    print("The dot product is commutative.")
else:
    print("The dot product is not commutative.")


In [ ]:
# Check distributive property: A • (B + C) = A • B + A • C
dot_product_A_BC = np.dot(A, B + C)
dot_product_AB_plus_AC = np.dot(A, B) + np.dot(A, C)

print(dot_product_A_BC)
print(dot_product_AB_plus_AC)


if dot_product_A_BC == dot_product_AB_plus_AC:
    print("The dot product is distributive.")
else:
    print("The dot product is not distributive.")

In [ ]:

# Define two vectors
A = np.array([1, 2, 3])
B = np.array([-4, -5, -6])
C = np.array([5,5,5])


# Calculate the cosine similarity
cosine_similarity = np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))

print("Cosine similarity between A and B:", cosine_similarity)

# Calculate the cosine similarity
cosine_similarity = np.dot(A, C) / (np.linalg.norm(A) * np.linalg.norm(C))

print("Cosine similarity between A and C:", cosine_similarity)


In [ ]:

# Define three vectors
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(np.dot(A, B))
print(A@B)

## Part 2: Matrix Construction & Types (Lab Q1 & Q2)

**Task:** Recreating the logic from Lab Q2.
Construct a $3 \times 3$ matrix $A = [a_{ij}]$ such that $a_{ij} = i^2 - j^2$.

In [ ]:
# Initialize a 3x3 matrix of zeros
A = np.zeros((3, 3))

# Fill it using loops (Indices i and j)
# Note: Python is 0-indexed (0,1,2), but Math is usually 1-indexed (1,2,3).
# We will use Math indexing to match the manual Lab.

rows, cols = A.shape

for i in range(rows):
    for j in range(cols):
        # Math index = python index + 1
        math_i = i + 1
        math_j = j + 1

        A[i, j] = math_i**2 - math_j**2

print("Constructed Matrix A (i^2 - j^2):")
print(A)

# Checking properties
print(f"\nIs A symmetric (A == A.T)? {np.array_equal(A, A.T)}")
print(f"Is A skew-symmetric (A == -A.T)? {np.array_equal(A, -A.T)}")

In [ ]:
# Special Matrices
identity = np.eye(3)        # Identity Matrix
zeros = np.zeros((2, 3))    # Zero/Null Matrix
ones = np.ones((2, 3))      # Matrix of Ones

print("Identity Matrix:\n", identity)

## Part 3: Operations - Element-wise vs Dot Product

**Crucial Distinction:**
* `*` in Python often means **element-wise** multiplication.
* `@` or `np.dot` means **Matrix Multiplication** (Rows $\cdot$ Cols).

Referencing Lecture Slides: "Row of A 'mixes' with column of B".

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# 1. Addition
print("A + B:\n", A + B)

# 2. Scalar Multiplication
print("\n2 * A:\n", 2 * A)

# 3. Element-wise Multiplication (Hadamard Product)
print("\nA * B (Element-wise):\n", A * B)
# Calculation: [[1*5, 2*6], [3*7, 4*8]]

# 4. Matrix Multiplication (Dot Product)
print("\nA @ B (Dot Product):\n", A @ B)
# Calculation Row 1 * Col 1: (1*5) + (2*7) = 19

In [ ]:
# TensorFlow equivalents
A_tf = tf.constant([[1, 2], [3, 4]])
B_tf = tf.constant([[5, 6], [7, 8]])

# Matrix Multiplication in TF
result_tf = tf.matmul(A_tf, B_tf)

print("TensorFlow MatMul Result:")
print(result_tf)

## Part 4: Inverse, Determinant & Solving Systems (Lab Q12 & Q13)

**Q12:** Calculate Inverse of $A$ and verify $A \cdot A^{-1} = I$.
**Q13:** Solve $x + 2y = 4$ and $2x + 5y = 9$.

In [ ]:
# Define Matrix A from Q12
A = np.array([[2, 5],
              [1, 3]])

# 1. Calculate Determinant
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A:.2f}")

# 2. Calculate Inverse
A_inv = np.linalg.inv(A)
print("\nInverse of A:\n", A_inv)

# 3. Verification: A @ A_inv should be Identity
verification = A @ A_inv
print("\nVerification (A @ A_inv):\n", np.round(verification))

In [ ]:
# Solving System of Equations (Q13)
# System:
# 1x + 2y = 4
# 2x + 5y = 9

# Coefficient Matrix
Coeffs = np.array([[1, 2],
                   [2, 5]])

# Constants Vector
Results = np.array([4, 9])

# Solve for [x, y]
solution = np.linalg.solve(Coeffs, Results)

print(f"Solution: x = {solution[0]}, y = {solution[1]}")

: 

## Part 5: Deep Learning Context - Image as a Tensor

The lecture slide mentioned: "Images = 3D Tensors (Height $\times$ Width $\times$ Channels)".

Let's create a random "fake" image tensor.

In [ ]:
# Create a random tensor simulating a 64x64 pixel image with 3 RGB channels
# Values between 0 and 255 (standard pixel intensity)
fake_image = np.random.randint(0, 256, size=(64, 64, 3))

print(f"Image Tensor Shape: {fake_image.shape}")

# Slicing Tensors: Get the 'Red' channel (channel 0)
red_channel = fake_image[:, :, 0]

print(f"Red Channel Shape: {red_channel.shape}")
print("Top left 3x3 pixels of Red Channel:\n", red_channel[:3, :3])

Image Tensor Shape: (64, 64, 3)
Red Channel Shape: (64, 64)
Top left 3x3 pixels of Red Channel:
 [[108 194 229]
 [232  14 142]
 [252 138 167]]


In [ ]:
fake_image[:,:,0]

array([[108, 194, 229, ..., 113, 144, 177],
       [232,  14, 142, ..., 175,  41, 212],
       [252, 138, 167, ..., 198, 197, 240],
       ...,
       [126, 124, 112, ..., 149, 120, 158],
       [103,  41, 188, ...,  87,  70, 158],
       [197, 207,  62, ...,  94, 177, 252]])

In [ ]:
fake_image

array([[[108,  47, 163],
        [194,   5, 205],
        [229, 211,  61],
        ...,
        [113, 197, 171],
        [144, 172, 177],
        [177, 108, 249]],

       [[232, 120,  22],
        [ 14, 181,  14],
        [142,  44, 119],
        ...,
        [175, 168,   1],
        [ 41, 205, 225],
        [212,  63, 135]],

       [[252, 173,  64],
        [138, 123, 100],
        [167,  75,  96],
        ...,
        [198, 117, 123],
        [197, 237, 237],
        [240,  29,  50]],

       ...,

       [[126, 152, 255],
        [124,  28,  91],
        [112,   5, 240],
        ...,
        [149,  18, 204],
        [120, 174,  34],
        [158, 117, 124]],

       [[103, 144,  64],
        [ 41,   5, 177],
        [188,  74, 135],
        ...,
        [ 87, 161,  64],
        [ 70, 107, 117],
        [158,  15, 210]],

       [[197, 216,  84],
        [207, 107,  47],
        [ 62,  46, 201],
        ...,
        [ 94,   2, 188],
        [177,  69, 154],
        [252, 254, 232]]